# Generated by Django 4.0 on 2022-01-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registercandidate',
            old_name='jobtype',
            new_name='jobtypes',
        ),
    ]
