# Generated by Django 4.0.1 on 2022-01-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registeremployer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registercandidate',
            name='comments',
        ),
        migrations.AddField(
            model_name='registeremployer',
            name='company_name',
            field=models.TextField(default='Sample_Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeremployer',
            name='no_of_vacancies',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OpenJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isVerified', models.BooleanField(default=False)),
                ('open_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('close_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.registeremployer')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('apply_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('jobname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.registeremployer')),
            ],
        ),
    ]
