# Generated by Django 3.2.10 on 2022-01-08 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registeremployer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenJobs',
            fields=[
                ('registeremployer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.registeremployer')),
                ('isVerified', models.BooleanField(default=False)),
            ],
            bases=('accounts.registeremployer',),
        ),
        migrations.AddField(
            model_name='registeremployer',
            name='company_name',
            field=models.TextField(default='TestCompany'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeremployer',
            name='no_of_vacancies',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
