# Generated by Django 4.0.1 on 2022-01-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_registercandidate_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openjobs',
            name='jobname',
            field=models.TextField(default='Sample Job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openjobs',
            name='salary',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
