# Generated by Django 4.0.1 on 2022-01-10 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_appliedjobs_apply_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openjobs',
            name='close_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='openjobs',
            name='open_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='openjobs',
            name='salary',
            field=models.IntegerField(default=1000),
        ),
    ]
