# Generated by Django 4.0.1 on 2022-01-11 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_openjobs_close_date_alter_openjobs_open_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openjobs',
            name='close_date',
        ),
        migrations.RemoveField(
            model_name='openjobs',
            name='jobname',
        ),
        migrations.RemoveField(
            model_name='openjobs',
            name='open_date',
        ),
        migrations.RemoveField(
            model_name='openjobs',
            name='salary',
        ),
        migrations.AddField(
            model_name='registeremployer',
            name='close_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registeremployer',
            name='jobname',
            field=models.TextField(default='Sample Job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeremployer',
            name='open_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
