# Generated by Django 4.0.1 on 2022-01-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_openjobs_close_date_remove_openjobs_jobname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeremployer',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OpenJobs',
        ),
    ]
