# Generated by Django 4.0.1 on 2022-01-11 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_registeremployer_isverified_delete_openjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeremployer',
            name='close_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registeremployer',
            name='open_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
