# Generated by Django 4.0.1 on 2022-01-11 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_registeremployer_close_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeremployer',
            name='close_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registeremployer',
            name='open_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
