# Generated by Django 4.0.1 on 2022-01-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_registeremployer_close_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeremployer',
            name='job_status',
            field=models.BooleanField(default=False),
        ),
    ]
