# Generated by Django 4.0.1 on 2022-01-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_registeremployer_job_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeremployer',
            old_name='job_status',
            new_name='job_closed',
        ),
    ]
